const CONSTANTS = {
  
  TODAY : "DD MMM, YYYY",
  TIME_NOW : "HH:mm",
  MEETING_IN_PROGRESS: 2,
  MEETING_WILL_FOLLOW: 1,
  ROOM_AVAILABLE: 0,
  INTERVAL_BACKGROUND_RESET: 60000,
  TIME_FOR_WILL_FOLLOW: 45

}

export default CONSTANTS;
