const CONSTANTS = {
  
  TODAY : "DD MMM, YYYY",
  TIME_NOW : "HH:mm",
  MEETING_IN_PROGRESS: 2,
  MEETING_WILL_FOLLOW: 1,
  ROOM_AVAILABLE: 0,
  INTERVAL_BACKGROUND_RESET: 60000,
  MIN_QUICKBOOK_DURATION: 15,
  BUTTON_COLOR: ["success", "warning", "error"],
  MAX_QUICKBOOK_DURATION: 40
}

export default CONSTANTS;
