const SIZE={
    HEIGHT_ADMIN_BUTTON:"50px",
    HEIGHT_TABLE_BUTTON:"30px",
    WIDTH_TABLE_BUTTON:"150px",
    WIDTH_ROUNDED_TABLE_BUTTON:"250px",
    HEIGHT_ROUNDED_TABLE_BUTTON:"40px",
    HEIGT_CARD:"130px",
    WIDTH_CARD:"332px",
    BORDER_RADIUS_CARD:"40px"
}
export default SIZE